In [106]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [126]:
df_gender = pd.read_csv("/kaggle/input/titanic/gender_submission.csv")
df_test = pd.read_csv("/kaggle/input/titanic/test.csv")
df_train = pd.read_csv("/kaggle/input/titanic/train.csv")

In [127]:
df_gender

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [128]:
df_test.head()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [129]:
df_train.head()
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [130]:
print(len(df_gender),len(df_train),len(df_test))

418 891 418

In [131]:
df_train['Sex'] = df_train['Sex'].map({'male': 1, 'female': 2})

In [132]:
cols = ["Pclass", "Sex", "Age"]
X_train = df_train[cols]
y_train = df_train["Survived"]

In [133]:
# X_train.head()
y_train.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [134]:
X_train.isna().sum()

Pclass      0
Sex         0
Age       177
dtype: int64

In [135]:
X_train =  X_train.fillna(X_train.mean())

In [136]:
X_train.isna().sum()

Pclass    0
Sex       0
Age       0
dtype: int64

In [137]:
from sklearn.linear_model import LogisticRegression

In [138]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [143]:
X_test = df_test[cols]
df_test['Sex'] = df_test['Sex'].map({'male': 1, 'female': 2})

In [144]:
X_test =  X_test.fillna(X_train.mean())

In [148]:
prediction = model.predict(X_test)
len(prediction)
prediction


df_gender['Survived'] = prediction
df_gender.to_scv("gender_submission.csv", index=False)

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]